"""schema inicial

Revision ID: 7119aa16f4e6
Revises: 
Create Date: 2026-07-08 16:51:52.262585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7119aa16f4e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('carga_exigida', sa.Integer(), nullable=False),
    sa.Column('fase', sa.Enum('5', '6_7', name='fase_area'), server_default='6_7', nullable=False),
    sa.Column('pre_requisito', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('carga_exigida > 0', name=op.f('ck_area_carga')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_areas')),
    sa.UniqueConstraint('nome', name=op.f('uq_areas_nome'))
    )
    op.create_index('uq_area_prereq', 'areas', ['pre_requisito'], unique=True, postgresql_where=sa.text('pre_requisito'))
    op.create_table('ciclos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('rascunho', 'em_andamento', 'encerrado', name='status_ciclo'), server_default='rascunho', nullable=False),
    sa.Column('passo_bootstrap', sa.Integer(), nullable=True),
    sa.Column('escala_desatualizada', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), nullable=True),
    sa.Column('encerrado_em', sa.TIMESTAMP(), nullable=True),
    sa.CheckConstraint('data_fim > data_inicio', name=op.f('ck_ciclo_datas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ciclos'))
    )
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_docentes')),
    sa.UniqueConstraint('nome', name=op.f('uq_docentes_nome'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('perfil', sa.Enum('administrador', 'coordenacao', 'consulta', name='perfil_usuario'), server_default='consulta', nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email'))
    )
    op.create_table('afastamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ferias', 'licenca', 'outro', name='tipo_afastamento'), server_default='ferias', nullable=False),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_retorno', sa.Date(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), nullable=True),
    sa.CheckConstraint('data_retorno >= data_inicio', name=op.f('ck_afast_datas')),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclos.id'], name=op.f('fk_afastamentos_ciclo_id_ciclos')),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], name=op.f('fk_afastamentos_docente_id_docentes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_afastamentos'))
    )
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('matricula', sa.String(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.Column('ordenamento', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclos.id'], name=op.f('fk_alunos_ciclo_id_ciclos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alunos')),
    sa.UniqueConstraint('ciclo_id', 'matricula', name='uq_aluno_ciclo_matricula')
    )
    op.create_index('idx_alunos_ordenamento', 'alunos', ['ordenamento'], unique=False)
    op.create_table('atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.Column('quando', sa.Date(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('ciclo', 'edicao', 'remanejo', 'sync', name='tipo_atividade'), server_default='edicao', nullable=False),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclos.id'], name=op.f('fk_atividade_ciclo_id_ciclos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atividade'))
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('academico', 'feriado', 'reuniao', 'recesso', 'outro', name='tipo_evento'), nullable=False),
    sa.Column('origem', sa.Enum('manual', 'google', 'api_feriados', name='origem_evento'), server_default='manual', nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('bloqueia_estagio', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('google_event_id', sa.String(), nullable=True),
    sa.CheckConstraint('data_fim >= data_inicio', name=op.f('ck_evento_datas')),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclos.id'], name=op.f('fk_eventos_ciclo_id_ciclos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eventos')),
    sa.UniqueConstraint('ciclo_id', 'nome', 'data_inicio', name='uq_evento_ciclo_nome_data')
    )
    op.create_table('fila_remanejo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.Column('quando', sa.Date(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclos.id'], name=op.f('fk_fila_remanejo_ciclo_id_ciclos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fila_remanejo'))
    )
    op.create_table('historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('aluno_nome', sa.String(), nullable=False),
    sa.Column('matricula', sa.String(), nullable=True),
    sa.Column('areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('carga_horaria_total', sa.Integer(), nullable=True),
    sa.Column('situacao', sa.Enum('ciclo_completo', 'pendente', name='situacao_historico'), nullable=False),
    sa.Column('encerramento', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclos.id'], name=op.f('fk_historico_ciclo_id_ciclos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historico'))
    )
    op.create_table('locais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.Column('campo', sa.String(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('preceptor', sa.String(), nullable=True),
    sa.Column('dia_semana', sa.Enum('segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado', 'domingo', name='dia_semana_tipo'), nullable=False),
    sa.Column('turno', sa.Enum('manha', 'tarde', 'integral', 'noite', name='turno_tipo'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('carga_horaria', sa.Integer(), nullable=False),
    sa.Column('numero_encontros', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('capacidade > 0', name=op.f('ck_local_capacidade')),
    sa.CheckConstraint('hora_fim > hora_inicio', name=op.f('ck_local_horas')),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_locais_area_id_areas')),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclos.id'], name=op.f('fk_locais_ciclo_id_ciclos')),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], name=op.f('fk_locais_docente_id_docentes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locais'))
    )
    op.create_table('indisponibilidades_local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.CheckConstraint('data_fim >= data_inicio', name=op.f('ck_indisp_datas')),
    sa.ForeignKeyConstraint(['local_id'], ['locais.id'], name=op.f('fk_indisponibilidades_local_local_id_locais')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indisponibilidades_local'))
    )
    op.create_table('locais_dias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    # create_type=False: o TYPE dia_semana_tipo já foi criado na tabela 'locais' acima.
    sa.Column('dia_semana', postgresql.ENUM('segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado', 'domingo', name='dia_semana_tipo', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['locais.id'], name=op.f('fk_locais_dias_local_id_locais'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locais_dias')),
    sa.UniqueConstraint('local_id', 'dia_semana', name='uq_local_dia')
    )
    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('data_matricula', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('em_andamento', 'concluida', name='status_matricula'), server_default='em_andamento', nullable=False),
    sa.Column('data_conclusao_prevista', sa.Date(), nullable=True),
    sa.Column('data_conclusao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name=op.f('fk_matriculas_aluno_id_alunos')),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_matriculas_area_id_areas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matriculas')),
    sa.UniqueConstraint('aluno_id', 'area_id', name='uq_matricula_aluno_area')
    )
    op.create_table('alocacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim_prevista', sa.Date(), nullable=False),
    sa.Column('travada', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ajuste_encontros', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('ativa', 'concluida', 'cancelada', name='status_alocacao'), server_default='ativa', nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name=op.f('fk_alocacoes_aluno_id_alunos')),
    sa.ForeignKeyConstraint(['local_id'], ['locais.id'], name=op.f('fk_alocacoes_local_id_locais')),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], name=op.f('fk_alocacoes_matricula_id_matriculas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alocacoes')),
    sa.UniqueConstraint('aluno_id', 'local_id', name='uq_alocacao_aluno_local')
    )
    op.create_table('sessoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alocacao_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fim', sa.Time(), nullable=True),
    sa.Column('horas', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.Enum('prevista', 'cumprida', 'remanejada', 'cancelada', name='status_sessao'), server_default='prevista', nullable=False),
    sa.ForeignKeyConstraint(['alocacao_id'], ['alocacoes.id'], name=op.f('fk_sessoes_alocacao_id_alocacoes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessoes'))
    )
    op.create_index('idx_sessao_alocacao_data', 'sessoes', ['alocacao_id', 'data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sessao_alocacao_data', table_name='sessoes')
    op.drop_table('sessoes')
    op.drop_table('alocacoes')
    op.drop_table('matriculas')
    op.drop_table('locais_dias')
    op.drop_table('indisponibilidades_local')
    op.drop_table('locais')
    op.drop_table('historico')
    op.drop_table('fila_remanejo')
    op.drop_table('eventos')
    op.drop_table('atividade')
    op.drop_index('idx_alunos_ordenamento', table_name='alunos')
    op.drop_table('alunos')
    op.drop_table('afastamentos')
    op.drop_table('usuarios')
    op.drop_table('docentes')
    op.drop_table('ciclos')
    op.drop_index('uq_area_prereq', table_name='areas', postgresql_where=sa.text('pre_requisito'))
    op.drop_table('areas')
    # ### end Alembic commands ###

    # Os TYPEs ENUM foram criados implicitamente junto das tabelas; removê-los aqui.
    for type_name in (
        'turno_tipo', 'dia_semana_tipo', 'fase_area', 'status_ciclo', 'status_matricula',
        'status_alocacao', 'status_sessao', 'tipo_afastamento', 'tipo_evento',
        'origem_evento', 'tipo_atividade', 'situacao_historico', 'perfil_usuario',
    ):
        op.execute(f'DROP TYPE IF EXISTS {type_name}')
