"""matricula interrompida

Revision ID: 9f5f9cff6d42
Revises: 7119aa16f4e6
Create Date: 2026-07-08 18:15:57.235697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5f9cff6d42'
down_revision: Union[str, Sequence[str], None] = '7119aa16f4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Novo valor no ENUM (o autogenerate NÃO detecta adição de valor de enum).
    # PG 12+ aceita ADD VALUE dentro de transação desde que o valor não seja
    # USADO na mesma transação — aqui só o adicionamos, então é seguro.
    op.execute("ALTER TYPE status_matricula ADD VALUE IF NOT EXISTS 'interrompida'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matriculas', sa.Column('motivo_interrupcao', sa.String(), nullable=True))
    op.add_column('matriculas', sa.Column('data_interrupcao', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matriculas', 'data_interrupcao')
    op.drop_column('matriculas', 'motivo_interrupcao')
    # ### end Alembic commands ###
    # NOTA: o Postgres não remove valor de ENUM de forma simples; o valor
    # 'interrompida' permanece em status_matricula (inofensivo). Removê-lo exigiria
    # recriar o tipo — evitado de propósito.
