"""ar7_docente_nullable_ar8_aluno_prioridade

Revision ID: 9fd4120b1555
Revises: f3b8c1d4e6a2
Create Date: 2026-07-13 17:36:20.779733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd4120b1555'
down_revision: Union[str, Sequence[str], None] = 'f3b8c1d4e6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('prioridade', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('locais', 'docente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locais', 'docente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('alunos', 'prioridade')
    # ### end Alembic commands ###
